# Site settings
title: Gianpaolo Filippa
description: 'Business Card Page'
url: ''
baseurl: ''
profilepic: '/images/gianpaolo3.jpg'
bkimage: '/images/gianpaolobg.jpg'
google_analytics: G-GEHJH7ZDF7
font_awesome: '2e3bf954c7.js'

author:
  name: 'Gianpaolo Filippa'
  email: gianpaolof@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  gianpaolof
  linkedin_username:  gianpaolofilippa
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
