# Site settings
title: Gianpaolo Filippa
email: "gianpaolof@gmail.com"
description: "My world in photos: motogp, mountains, street life"
url: "https://gianpaolof.github.io"
baseurl: ""
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  "gianpaolof"
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

google_analytics: G-5758K798LR

# Owner/author information
owner:
  name:   gianpaolo filippa
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

#fonts
font_awesome: '2e3bf954c7.js'

# Internal nav
nav:
  - HOME: "https://gianpaolof.github.io/"  
  - GALLERY: "https://gianpaolof.github.io/gallery/"  
  - ABOUT: "https://gianpaolof.github.io/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
 - jekyll-seo-tag
 - jekyll-sitemap
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
